configs:
  traefik_config:
    file: ./configs/traefik/traefik.yml
networks:
  mail:
    name: mail
  mysql:
    name: mysql
  redis:
    name: redis
  traefik:
    name: traefik
secrets:
  mysql_password:
    file: ./secrets/mysql_password
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user:
    file: ./secrets/mysql_user
  portainer_admin_password:
    file: ./secrets/portainer_admin_password
services:
  mailpit:
    expose:
      - 1025
    image: axllent/mailpit:v1.15.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.rule=Host(`mailpit.${APP_HOST:-localhost}`)
      - traefik.http.routers.mailpit.service=mailpit
      - traefik.http.services.mailpit.loadbalancer.server.port=8025
    networks:
      mail:
        aliases:
          - mailpit.${HOST:-localhost}
      traefik:
    volumes:
      - mailpit:/data
  mysql:
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
    image: percona:8.0.36-28
    networks:
      mysql:
        aliases:
          - mysql.${HOST:-localhost}
    ports:
      - 3306:3306
    secrets:
      - mysql_password
      - mysql_root_password
      - mysql_user
    volumes:
      - mysql_var_lib:/var/lib/mysql
      - mysql_var_log:/var/log/mysql
  phpmyadmin:
    environment:
      PMA_HOST: mysql.${HOST:-localhost}
    image: phpmyadmin:5.2.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`pma.${HOST:-localhost}`)
    networks:
      - mysql
      - traefik
  portainer:
    command: --admin-password-file=/run/secrets/portainer_admin_password
    image: portainer/portainer-ce:2.20.0
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer-dashboard.rule=Host(`portainer.${HOST:-localhost}`)
      - traefik.http.routers.portainer-dashboard.service=portainer
      - traefik.http.routers.portainer-api.rule=Host(`portainer.${HOST:-localhost}`) && PathPrefix(`/api`)
      - traefik.http.routers.portainer-api.service=portainer
    networks:
      - traefik
    secrets:
      - portainer_admin_password
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer:/data
  redisinsight:
    image: redislabs/redisinsight:1.14.0
    labels:
      - traefik.enable=true
      - traefik.http.services.redisinsight.loadbalancer.server.port=8001
      - traefik.http.routers.redisinsight.rule=Host(`redisinsight.${HOST:-localhost}`)
      - traefik.http.routers.redisinsight.service=redisinsight
    networks:
      - redis
      - traefik
  traefik:
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yml
    image: traefik:2.11.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${HOST:-localhost}`)
      - traefik.http.routers.traefik.service=api@internal
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik:/var/lib/traefik
      - /run/docker.sock:/run/docker.sock
volumes:
  mailpit:
  mysql_var_lib:
  mysql_var_log:
  portainer:
  traefik:
