include:
  - path: docker-compose.mailpit.yml
  - path: docker-compose.mysql.yml
  - path: docker-compose.phpmyadmin.yml
  - path: docker-compose.portainer.yml
  - path: docker-compose.redisinsight.yml
  - path: docker-compose.traefik.yml
name: localhost
secrets:
  mysql_database:
    file: ./secrets/mysql_database
  mysql_password:
    file: ./secrets/mysql_password
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user:
    file: ./secrets/mysql_user
  portainer_admin_password:
    file: ./secrets/portainer_admin_password
